version: '3.8'
services:
#  user-service:
#    build:
#      context: ../.
#      dockerfile: Dockerfile
#    container_name: user-service
#    ports:
#      - "9002:9002"
#    depends_on:
#      - user-db
#      - eureka-server
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
#    networks:
#      - general
  user-service:
    image: merttkayaa/user-service:latest
    container_name: user-service
    ports:
      - "9002:9002"
    depends_on:
      - user-db
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - general

  user-service-instance:
    image: merttkayaa/user-service-instance:latest
    container_name: user-service-instance
    ports:
      - "9003:9003"
    depends_on:
      - user-db
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - general

  user-db:
    image: 'postgres:13.1-alpine'
    container_name: user-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - general

  eureka-server:
    image: muholo/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: always
    networks:
      - general

  gateway-service:
    image: merttkayaa/gateway-service:latest
    container_name: gateway-service
    ports:
      - "8765:8765"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    restart: always
    depends_on:
      - eureka-server
      - user-service
      - user-service-instance
    networks:
      - general

networks:
  general:
     driver: bridge
